/** [07-P0-2] "What happened here" — one paragraph per POI category, written once and shown on
 * every card of that category. Report 07's point: the map records where things were and never
 * that anyone lived there. Fifty paragraphs cover all 448 places.
 *
 * Rules for anything added here:
 *  - Present tense, set in 117 CE. The reader is standing in it.
 *  - Concrete and sensory. Hours of the day, prices, smells, who is doing the work.
 *  - Google Business page voice: no hedging apparatus, no citations, no scholar-speak.
 *  - About the category, never about one place. It renders under hundreds of pins.
 *  - Roughly 110–130 words.
 */

export const CATEGORY_LIFE: Record<string, string> = {
  forum:
    "Business starts at first light. The magistrates' tribunal opens, cases are called, and the crowd that gathers to listen is half the point of coming. Money-changers work from tables under the porticoes, weighing coin from a dozen mints against the local rate. Notices are painted on the walls and whitewashed over when they go stale: elections, gladiator shows, a lost slave, a house to let. By the sixth hour the heat empties the open square and the arcades fill instead. Statues of the town's benefactors stand between the columns, and the men who paid for them expect to be greeted by name. Public slaves sweep at dusk. The forum is where a Roman town keeps its records, its gossip and its self-regard in the same place.",
  curia:
    "The doors stand open during a session, so the crowd outside can hear. Inside, the order of speaking is the order of rank, and a man's whole career is measured by how early his name is called. Members sit on tiered benches facing each other rather than a chair, which makes the room argumentative by design. Business is read out by a clerk: letters from governors, embassies waiting in the corridor, requests for temple money, permission for a town to build. Voting is done with the feet, one side of the room against the other. Nothing said inside leaves formally, and everything said inside is repeated by evening. In a provincial town the local council does the same work in a smaller room, and cares about it just as much.",
  basilica:
    "This is the town's indoor hall, and in winter it is where everyone goes. Court sits at one end on a raised platform, screened off with wooden partitions when the case is private. Around it, business goes on regardless — contracts witnessed, cargoes argued over, bankers at their tables, men sheltering from rain with nothing to do. The roof is carried on two storeys of columns, and the upper gallery is a good place to watch a trial without being counted as part of the crowd. Advocates are paid by reputation and perform accordingly; a good one draws an audience the way an actor does. Noise carries badly, which everyone complains about. Building one is the standard way for a rich citizen to be remembered.",
  temple:
    "The building itself is a house for the god, and most people never go inside. Everything public happens on the steps and at the altar in front: an animal led up, examined, killed cleanly, its organs read, the meat divided and eaten. The priest covers his head and a flute player keeps up a noise so no ill-omened word is heard. Worshippers leave what they can afford — a terracotta figure, a coin, a model of the body part they want healed — and the accumulated clutter is periodically cleared and buried on site. On festival days the doors are opened and the cult statue is dressed, garlanded, and sometimes carried out through the streets. The temple also holds money, which is why towns keep their treasury in one.",
  monument:
    "It was put up to be argued with. Public monuments carry an inscription at eye height naming who paid, what for, and by whose authority, because being read is the whole return on the investment. People meet at them, give directions by them, and shelter under them. Children climb them. The bronze fittings are stolen often enough that they are re-attached with lead. On anniversaries the base is garlanded and the local council makes a short speech nobody listens to. Monuments also date the town for you: a run of them along one street shows which families were rising in which decade, and which ones stopped. When a family falls out of favour, the name is chiselled out and the stone is quietly reused.",
  arch:
    "It carries no gate and defends nothing. An arch marks a threshold — a boundary, a road junction, the entrance to a forum — and it exists to make you look up while you pass under it. The attic carries the dedication in bronze letters set into cut sockets; the letters go missing and the sockets stay. The panels beneath show the campaign being celebrated, arranged so that the version of events the emperor prefers is the one at eye level. Traffic goes through it all day, ox carts scraping the jambs. A triumph passes under it once, if at all; the rest of its working life is as a landmark, a meeting point and a shaded spot for someone selling something.",
  palace:
    "The public rooms are enormous and the private ones are not. A visitor is walked through an audience hall built to make him feel small, waits with everyone else, and is admitted in order of usefulness. Behind that front, the household runs on hundreds of slaves and freedmen with narrow specialities — one for the lamps, one for the silver, one who remembers names. The kitchens are far from the dining rooms, so food arrives warm at best. Business never stops: petitions from provincial towns, judicial appeals, dispatches read aloud while the emperor is being shaved. Gardens and fountains take up as much ground as the buildings, because being able to waste that much space in a crowded city is the point.",
  circus:
    "Two hundred thousand people can watch, and on race days most of them do. Four stables — Red, White, Blue, Green — supply the teams, and supporters wear the colour, bet on it, and brawl about it. Seven laps, twelve chariots, the tightest turns at either end of the central barrier where the crashes happen. Between races there are acrobats, and the barrier itself carries obelisks, statues and the lap-counting eggs and dolphins that are tipped one by one. Seating is mixed, unlike the theatre, which makes the circus the best place in the city to meet someone. Drivers start as slaves and the successful ones die rich and famous. The track is watered and raked constantly; the smell is horse, dust and food.",
  amphitheater:
    "Doors open early and the programme runs all day. Morning is animal hunts, staged with scenery hauled up through trapdoors from the corridors below. Midday is executions, and it is the hour when the seats thin out and people go for lunch. The afternoon is the gladiators, matched by type and record like boxers, refereed, and stopped when a man raises a finger. Most fights are not to the death — a trained fighter is expensive — but a decision can go the other way and the crowd is consulted. Seating is strictly by rank: officials at the front, women at the top. Awnings are worked by sailors detailed for the job. Sand is spread thick and replaced between shows, and the whole building smells of it.",
  market:
    "Trade is regulated and everyone is aware of it. Weights and measures are checked against the standards kept by the aediles, and short measure gets you fined and named. Stalls are arranged by trade, with the fish and meat kept to one side and downwind where the town has any choice. Prices swing with the shipping season and are shouted rather than displayed. Much of the meat on sale has come from a sacrifice, so the religious calendar shows up in the supply. Slaves buying for a household argue harder than their owners would. The upper floors, where there are any, are offices and storage let by the town for rent. It opens at dawn and the good produce is gone by mid-morning.",
  column:
    "A single shaft, standing alone, carrying a statue or a story. The freestanding column is a Roman way of putting one thing above everything else in a crowded skyline, and where it is set matters as much as what is on it. Some carry a spiral relief read from the ground with difficulty and never meant to be read closely — the point is the sheer weight of narrative. Others carry a portrait, and the portrait is replaced when the politics change while the column stays. The drums are hollowed for an internal stair in the ambitious ones. At the base there is usually an inscription and, often enough, a burial. Around it, day to day, people sell things and arrange to meet.",
  library:
    "Books are scrolls, kept in labelled pigeonholes around the walls, and you read them standing at a desk or sitting in the courtyard with a slave to hold the roll. Greek and Latin collections are kept separately, often in facing rooms. Nothing is borrowed. A staff of copyists keeps the collection alive, because a scroll handled regularly lasts a couple of generations at best, and a library that stops copying is a library that is dying. Readers are respectable men and their secretaries; access is a favour that can be withdrawn. Libraries attach themselves to baths, temples and fora rather than standing alone, so a visit is folded into a day of other business. Lamps are forbidden inside for obvious reasons.",
  bathhouse:
    "The furnaces are lit before dawn and the water is hot by the eighth hour, which is when the town arrives. The circuit is a habit: undress and hand your clothes to an attendant who may or may not be watching them, exercise in the courtyard, sweat in the hot room, scrape the oil and dirt off with a curved bronze strigil, then the warm pool and the cold plunge. Entry costs a coin small enough that almost nobody is priced out, and on a benefactor's birthday it is free. There is food, drink, ball games, gambling, hair-plucking, business and shouting; a writer complaining about the noise from the flat above is complaining about all of it. Men and women bathe at different hours, or in separate wings.",
  theater:
    "Seating is the message: the front rows are reserved by law for the town council, and everyone can see who is sitting where. The building is a half-circle against a tall stone backdrop that also serves as a permanent set, and the acoustics are good enough that an actor can be heard without effort. The programme is mime and pantomime more than the old tragedies — bawdy, topical, sometimes politically sharp enough that performers get exiled. Audiences are loud, partisan, and quite prepared to shout a piece down. Awnings and perfumed water sprays are laid on when the sponsor is generous. Shows are attached to religious festivals and paid for by a magistrate who wants the credit, and his name is on the seating.",
  mausoleum:
    "The tomb is built where the traffic is: on the road out of town, facing the carriageway, close enough to read at walking pace. That is the design brief. Inside there may be a single chamber for one family or niches for dozens, with cremation urns or, increasingly, bodies laid out. Outside there is a portrait, an inscription giving the dead their offices and their years, and often a bench, because visitors come back. The family returns on the anniversary and at the February festival of the dead, brings wine and food, and eats a meal at the graveside. Endowments are left to keep it up and lawsuits follow when they are not honoured. A grand tomb is the last public building a family gets to commission.",
  aqueduct:
    "Water arrives day and night and never stops. The channel runs mostly underground, following a shallow gradient measured out with a levelling instrument over tens of miles, and it goes up on arches only where the ground drops away. Inspection shafts sit at intervals; gangs work the line constantly, cutting out the lime crust that thickens on the walls and narrows the flow. At the town end the water is divided in a distribution tank — public fountains first by law, then baths, then private houses whose owners have paid for a pipe of a fixed and stamped size. Illegal tappings are a permanent scandal. What arrives is not stored but runs continuously, and the overflow flushes the drains.",
  port:
    "Sailing season runs roughly from spring to autumn and the port lives by it. Ships anchor in the outer basin and warp in, or are unloaded by lighters if they draw too much. Cargo comes ashore under the eye of a customs officer taking a percentage, is weighed, and goes into warehouses along the quay. Grain for Rome is the priority and everything else waits behind it. Amphorae are stacked, checked, and the broken ones dumped. Gangs of porters work by the load; shipping agents and guild offices cluster round the harbour square, advertising routes in mosaic on the floor. Divers work the bottom for dropped cargo. In winter the ships are hauled out and the whole place goes quiet.",
  lighthouse:
    "The fire burns at the top all night and is visible for miles from a coastline that otherwise gives a pilot nothing to steer by. Fuel — wood, or oil where wood is scarce — is carried up an internal ramp or hoisted, and a crew lives on site to keep the fire fed and the reflecting surfaces clean. A tower on a mole doubles as a harbour marker and a breakwater. Mariners complain that a steady light at sea can be mistaken for a low star, and that is a real hazard. By day the tower is a landmark instead. It appears on coins and on the mosaics of shipping agents, because a port with a lighthouse is advertising that it can be entered at night.",
  canal:
    "Cut to shorten a journey, to bypass a river mouth that silts, or to drain ground that floods. Digging is done by soldiers or by contracted labour in seasons when the water is low, and the spoil is banked along the sides to make a towpath. Barges are hauled by men or oxen, moving grain, stone, timber and wine at a fraction of the cost of the same distance by road. Sluices control the level where the canal meets a tidal river. Maintenance is endless — silt, weed and collapsed banks — and a canal that is not dredged returns to marsh within a generation. Towns along it grow fast, and the tolls charged at each end are worth having.",
  necropolis:
    "The dead are outside the walls because the law requires it, so the approach to every town is lined with them. Tombs face the road in rows, grand ones in front and simpler markers behind, all of them addressed to the passer-by. Burial clubs let ordinary people and slaves pay a monthly subscription for a place in a communal vault and a decent funeral; the alternative is a pit. Families come out on anniversaries and at the February festival, eat at the graveside, and pour wine into a pipe set into the ground. Undertakers, stonecutters and letter-cutters work nearby and compete on price. Ground is bought by the foot, and the frontage on the road costs the most.",
  warehouse:
    "Rows of identical rooms off a central courtyard, with a wide gate, a weighing station and a guard. Floors are raised on low walls so air passes underneath and grain does not sweat. Space is rented by the room or the amphora, and the operator takes a fee for storage and another for security; valuables go into strongrooms with iron doors. Everything is inventoried by clerks who are usually slaves and who are very good at it. Grain, oil, wine, marble, salt fish, timber — most of it in transit rather than stored long. Rats, damp and fire are the constant enemies and there are contracts covering all three. Around the entrance, porters wait for work by the day.",
  road:
    "The surface is cambered, drained on both sides, and built to be repaired rather than to last forever. Milestones give the distance to the nearest town and the name of the emperor who last paid for resurfacing. Traffic is mostly feet and hooves; wheeled freight is slow and heavy and, in some towns, banned during daylight. Official messengers use the state relay and change horses at posting stations set roughly a day apart, which is what makes the empire governable. Everyone else walks about twenty miles a day and stops at an inn of doubtful quality. Tombs, shrines and roadside bars line the approaches to any town. Bandits are a real risk on quiet stretches and the army patrols the worst of them.",
  gate:
    "The gate is where a town shows itself and where it counts what comes in. Traffic is funnelled between towers into arched passages — the wide ones for carts, the narrow ones for people — and closed at night with timber leaves shod in iron. A customs post takes duty on goods; a clerk records what passes. The outward face is the decorated one, with an inscription naming the emperor and the town, because this is the first thing a visitor reads. Guards are usually the town's own watchmen rather than soldiers. Just outside, the tombs begin; just inside, the shops. In a town whose walls have long stopped mattering militarily, the gate is kept up anyway, for the look of the thing.",
  synagogue:
    "A meeting house rather than a temple, and the building follows the community rather than a plan. There is a hall with benches along the walls, a niche or chest holding the scrolls, and often a dining room, because communal meals matter as much as the readings. Scripture is read and translated aloud, and interpretation is argued over openly. The community keeps its own funds for the poor and its own burial ground, and sends money to Jerusalem — a practice that survives the destruction of the Temple in a changed form. Non-Jews attend as interested outsiders and are welcome without being members. Inscriptions record donors, including women holding titles of office. Under Roman law the community's right to meet and to keep the sabbath is protected.",
  fort:
    "A legionary fortress holds five thousand men and is laid out to the same plan everywhere, so a transferred soldier knows his way around on the first day. Two main streets cross at the headquarters building, where the standards and the pay chest are kept in a sunken strongroom under guard. Around it: the commander's house with a courtyard garden, granaries raised on stone piers, a hospital, workshops, and long barrack blocks divided into rooms for eight men who cook and mess together. Training is daily, and building work is constant — soldiers make their own bricks, tiles and boots. A civilian town grows against the walls, with bars, traders and the unofficial families of men who are not legally allowed to marry.",
  bridge:
    "Piers are set on cofferdams — a ring of driven piles, pumped dry, filled with concrete that sets under water. They are built with a cutwater pointing upstream to split the current and the ice. The span above may be stone arches or timber on stone, and timber is not a poor relation: it is cheaper, faster, and replaceable. Roads approach on an embankment so the crossing stays level. Tolls are common, shrines at either end are usual, and the inscription names whoever paid. Floods are the enemy; a bridge is inspected after every big one, and the scour around the piers is packed with rubble. A bridge fixes a town's position for a thousand years, which is why so many are still standing.",
  fountain:
    "This is where most of the town gets its water, and it runs continuously because the aqueduct cannot be switched off. A basin catches the flow, jars are filled from spouts, and the overflow goes into a channel that flushes the street. Queues form early and the fountain is where the neighbourhood's news circulates. The stonework wears into grooves where thousands of hands and rope have rested on the rim. Animals drink at a lower trough. Bigger show-fountains at street corners and road junctions are put up by magistrates and carry their names; the water is the gift and the inscription is the receipt. Blocking, fouling or tapping a public fountain is an offence people are actually prosecuted for.",
  mine:
    "Work goes on underground by lamplight in shifts, and the lamp is also the clock. Galleries follow the ore, propped with timber, drained by wooden screws and bucket wheels worked by hand in stages up the shaft. Ventilation is a second shaft and a fire to draw the air. The labour is convicts, slaves and paid men working side by side on different terms, and the paid men do the skilled cutting. Above ground the ore is crushed, washed in long channels, and smelted, and the smoke kills the vegetation for miles. Mines of any size are imperial property, leased to contractors under written regulations covering shifts, drainage, bath-house charges and who may open a new gallery. Settlements grow around them fast and empty just as fast.",
  wall:
    "A town wall is a claim as much as a defence. It is faced in stone, cored with rubble and concrete, and pierced by gates that are more decorated than the rest of it put together. Towers project so that anyone at the base can be shot from the side. In most of the empire in this century the walls are old, unmanned, and half built over — shops lean against them and houses are cut into them — because the frontier is a long way off and the danger is not here. On the frontier itself a wall is something else entirely: a continuous barrier with ditches, gates at intervals, patrol tracks and manned turrets, built to control movement rather than to stop an army.",
  city:
    "Somewhere between ten thousand and a million people, packed inside a boundary, living mostly in rented rooms above shops. The street is the living room: cooking is done at a bar downstairs, water is fetched from the fountain, and the lavatory is public and sociable. Blocks are five or six storeys where the ground is expensive, built fast and prone to fire and collapse; the ground floor is retail and the higher you live the worse it gets. Nights are loud with delivery carts banned from the daytime streets. The town council pays for the water, the baths and the games, and expects deference for it. Everyone who can afford to leaves in August, and everyone who cannot complains about the smell.",
  house:
    "The front door opens onto a corridor and then a roofed hall with a pool under an opening in the roof, and that hall is a public room — clients arrive at dawn to greet the owner, and the whole plan is arranged so they can be received and impressed. Behind it, a colonnaded garden with a dining room off it, three couches around a low table, guests reclining on the left elbow. Rooms are small, dark and multi-purpose; furniture is moved as needed. Walls are painted to open the space out with fake architecture and landscapes. Windows are shuttered rather than glazed. Cooking, laundry and the slaves' quarters are pushed to the edges. Street frontage is let out as shops, because it is too valuable to waste.",
  villa:
    "A working estate with a comfortable house attached, and the proportions vary with how rich the owner is and how often he visits. The farm side has presses for oil and wine, threshing floors, storage sunk into the ground, stables and quarters for the workforce. The residential side has baths, dining rooms sited for the view, mosaics, and a garden with water in it. A manager runs the place year-round and reports; the owner arrives for the vintage and for the summer. Produce goes to market or to the owner's town house, and the accounts are kept in detail. Some villas are pure retreat with no farm at all, built on a cliff or a lake specifically to be looked at from a boat.",
  collegium:
    "An association of men in the same trade or worshipping the same god, and usually both at once. It has a clubhouse with a dining room, a shrine, a set of written rules and an elected treasurer who is chased when the accounts do not balance. Members pay a joining fee and monthly dues; in return they get dinners on the founder's birthday, a vote, a title if they are lucky, and above all a funeral and a place in the collective tomb. Fines are levied for drunkenness at meetings and for starting arguments about seating. Many members are freedmen for whom this is the only office they will ever hold. The authorities watch them, since any organised group is a political risk.",
  naval_base:
    "The fleet is quartered here and the base is built around getting ships out of the water. Slipways and covered sheds keep hulls dry through the winter, because a warship left afloat waterlogs and slows. Crews are provincials serving long terms, not citizens, and they train at the oar constantly in the harbour. Workshops turn out rope, pitch, sailcloth and oars in quantity; timber is stockpiled seasoned. The main fleets patrol against piracy, carry dispatches and move troops, and in practice they spend far more time on transport than on battle. Detachments are posted away for years at a stretch. A large base needs a lighthouse, a mole and a town, and it gets all three.",
  signal_tower:
    "A small stone tower with a timber top, sited so that it can see the next one along the line. Half a dozen men live in it. They watch the ground in front, and they watch the tower on either side. A signal — fire and smoke at night, something visible by day — passes a warning down the chain far faster than a rider can, though it can only carry a message that was agreed in advance. The rest of the time it is a lookout post on a road, a river crossing or a frontier line, and the work is boredom punctuated by inspections. Supplies come up from the fort behind. Towers on a frontier stand within sight of each other for hundreds of miles.",
  auxiliary_fort:
    "Five hundred men, sometimes a thousand, recruited from a province rather than from citizens, and often stationed a long way from where they were raised. Cavalry units get a bigger fort and far more stabling; the smell tells you which kind you are in before the plan does. The layout copies a legionary fortress at a quarter of the size — headquarters, commander's house, granaries, barracks, a bath house usually built outside the walls because of the fire risk. Duties are patrolling, escorting, customs, and policing rather than pitched battle. After twenty-five years a man is discharged with citizenship for himself and his children, recorded on a bronze diploma he keeps for life. A village grows outside the gate within a decade.",
  dam:
    "Built to hold water for a town, a farm or a mine, and shaped by what the local rock allows: a straight wall of masonry backed with earth, or a curved one where the gorge is narrow. The core is concrete and rubble, faced in cut stone, and the upstream face is often waterproofed with mortar. Water is drawn from a tower with sluices at different heights, so the supply keeps running as the level drops and the silt stays at the bottom. Overflow channels carry the winter flood past the wall rather than over it — the detail that decides whether a dam survives. Silt is the long enemy; a reservoir has a working life and everybody involved knows it.",
  watermill:
    "The wheel turns all day and the miller's household lives to its noise. Water is brought in along a channel, dropped onto the wheel from above where the fall allows, and the gearing turns a horizontal drive into a vertical one for the millstones. One mill can grind for a small town. Where the flow is strong, mills are stacked in a cascade, each using the water the one above has finished with, and a site like that can feed a city. Grain arrives by cart and leaves as flour, with the miller taking a share rather than a fee. Stones are dressed regularly, and a mill also saws stone and works trip-hammers. Floods, drought and the millpond silting are the recurring troubles.",
  cistern:
    "Underground, vaulted, and much larger inside than anything visible above suggests. The walls are lined with waterproof mortar, the corners rounded so nothing can lodge, and the roof carried on rows of piers. Water arrives by aqueduct or off the roofs and is held against the dry months, for a fleet, a bath house, a fort or a whole town. Sediment settles in a trap before the main tank, and the tank is drained and scrubbed on a cycle by men who go down by ladder. Access is through shafts with stairs, and it is cool enough down there that things are stored in them. A town on a dry site lives or dies by its cisterns, and they are among the first things built.",
  quarry:
    "The rock is worked in benches from the top down, so that gravity does the moving. Channels are cut around a block with a pick, then it is split from the bed with iron wedges driven into a line of holes, sometimes with wooden wedges soaked to swell. Blocks are dressed roughly on the spot — no one hauls waste — and marked with the quarry, the gang, the date and the consular year, which is how the empire keeps track of what it owns. Sledges, rollers and ox teams take them to a river or the sea, because moving stone overland is the expensive part. Fine marbles are imperial monopolies. Abandoned faces still show the last unfinished cut, stopped mid-job and never resumed.",
  garum_factory:
    "Rows of stone vats sunk into the ground beside the sea, and the smell reaches a long way inland. Small fish and the guts of larger ones are layered with salt and left in the sun for weeks; the liquid that separates off is drawn away as fish sauce and the residue is sold cheaply as paste. Grades run from a luxury sauce that costs more than good wine down to the version bought by everyone else. Tunny is netted in season from lookout towers on the headland, and the fishing, salting, potting and shipping all happen within a few hundred metres. Amphorae are stamped with the maker's name. Towns built on this are rich, and they are built downwind of themselves.",
  salina:
    "Shallow pans are cut into the flats behind a beach or a lagoon and filled at high tide through a gate. The water is walked through a sequence of pans, each shallower and saltier than the last, and the sun does the rest over the summer. In late season the crust is raked into ridges, left to drain, then carried off in baskets. The work is hot, glaring and hard on the feet, and it is done by contracted labour on a short season. Salt preserves fish and meat, cures hides and pays part of the state's revenue, so the pans are regulated and often leased from the state. A salina needs sun, wind and a tide, and it shuts down entirely when it rains.",
  kiln:
    "The workshop runs as a production line. Clay is dug locally, weathered over winter, kneaded and thrown, or pressed into moulds for the decorated wares. Vessels are dried under cover, stamped with the potter's name, stacked in the kiln around a central flue and fired for days with the temperature judged by eye and by test pieces pulled from a port in the side. A big firing holds tens of thousands of pots and a bad one loses the lot. Wasters are dumped in heaps beside the works. Some workshops export across half the empire and their stamps turn up thousands of miles away. Fuel is the limit on everything, so kilns sit near woodland and move when it runs out.",
  estate:
    "Land held in one ownership and worked as a unit, whether the owner is a senator, an emperor or a town. Day to day it is run by a manager who keeps the accounts, allots the tasks and answers for the shortfall. The workforce is mixed — slaves in gangs, tenant farmers on shares, and seasonal labour hired for the harvest and the vintage. Tenants owe a proportion of the crop and a fixed number of days' work, and the terms are posted publicly, which is how we know them. Buildings cluster: presses, granaries, a smithy, quarters, a shrine. Disputes over water and over how many days are owed go to the estate's own procurator first and to the emperor if that fails.",
  tomb:
    "Roman burial is a family matter conducted in public. The dead are carried out of town, cremated or laid in the ground, and mourned with formal noise; the funeral of anyone important is a procession with masks of the ancestors carried by hired men. The tomb that follows is designed to be read by strangers on the road: name, age, offices, sometimes a trade shown in relief, often a line addressed directly to the passer-by. Ordinary people appear here as they nowhere else — a baker with his ovens carved on the front, a freedman naming the woman he could finally marry, a child's age given in days. Anniversaries bring the family back with food and wine.",
  sanctuary:
    "A sanctuary is a precinct, not a building — an enclosed area with a boundary that matters legally. Inside it, rules apply: certain acts are forbidden, debtors and runaways may claim protection, and in some the birth or death of anyone is not permitted. Pilgrims arrive on foot, sometimes over days, and there is accommodation, water, and a market selling exactly what they need to offer. Priesthoods are local and hereditary or annual and political depending on the place. Treasuries hold the accumulated gifts of centuries, catalogued on stone. Festivals draw crowds from a whole region and bring games, contests and trade with them. Between festivals the place is quiet, staffed by a caretaker and visited by a trickle of travellers.",
  oracle:
    "You come with a question, and the form of the question matters as much as the answer. There is a fee, a preliminary sacrifice, and a wait — sometimes days, sometimes only on certain days of the year. The consultation itself is controlled: the enquirer rarely meets the speaker directly, and the response arrives through an intermediary, in verse or in writing, and often ambiguously enough to survive being wrong. Cities consult about colonies, wars and plagues; individuals about marriage, illness, travel and lost property. The sanctuary grows rich on the gifts of those whose answers came out well. Sceptics are common and say so openly. By this century several famous oracles are quieter than they were, and people notice.",
  asklepieion:
    "A healing sanctuary where the treatment is a night's sleep. Patients purify themselves, sacrifice, and then lie down in a long open hall to wait for a dream in which the god appears and either heals them or prescribes. In the morning the priests interpret. The prescriptions are practical as often as not — diet, exercise, cold baths, a walk — and there are doctors on site alongside the priests, with no sense that the two are in competition. Cured patients pay for a plaque recording what was wrong and what was done, and the walls fill with them; a model of the healed limb or organ is the cheaper option. Snakes and dogs live in the precinct and are part of the treatment.",
  battle:
    "A Roman army fights the way it camps: in lines, by drill, on ground chosen if possible. The legions form up in cohorts with gaps that let ranks rotate, throw a volley of heavy javelins at close range, and then close with the short sword, pushing behind the shield. Auxiliaries hold the flanks and do most of the cavalry work and most of the skirmishing. Battles are short and decided by whether one line breaks, and the killing happens in the pursuit rather than the fighting. The camp is dug and palisaded every night regardless. Afterwards the dead are stripped and the field is looted for days; the ground is remembered locally long after the campaign is a paragraph in someone's history.",
  shipwreck:
    "A merchantman goes down with everything aboard and the sea keeps most of it. Cargo is usually amphorae — wine, oil, fish sauce — stacked in layers in sand, or roof tiles, or marble in the round, or ingots stamped with the smelter's name. Timbers survive where the mud or the cargo covers them, and the hull shows how it was built: planks edge-joined with mortise and tenon before the frames go in, a way of building that is slow, strong and about to be abandoned. Personal things come up too — a cooking pot, a lamp, coins that date the last voyage to within a few years. Most losses happen in autumn, close inshore, on a coast the crew knew.",
};

/** The paragraph for a category, or undefined when there isn't one yet. Callers must handle
 * undefined — plenty of categories arrive from the thematic files with no entry here. */
export function lifeForCategory(category: string | undefined | null): string | undefined {
  if (!category) return undefined;
  return CATEGORY_LIFE[String(category).toLowerCase()];
}
