/** All 28 legions of the Roman army in 117 CE, with their fortress location and the
 * matching pois.geojson feature id. Derived directly from the fortress records already
 * researched and cited in public/data/pois.geojson (category "fort") — no new research,
 * this file just gives that existing data a dedicated, browsable index. Legion count (28)
 * matches the historical record for 117 CE: Trajan lost none outright, but II Traiana Fortis
 * was newly raised for the Parthian war and the empire settled at 28 standing legions by
 * this snapshot. */

export type Legion = {
  numeral: string;
  epithet: string;
  legion: string;
  poiId: string;
  fortressLatin: string;
  province: string;
  modernLocation: string;
  center: [number, number];
};

export const LEGIONS: Legion[] = [
  {
    numeral: "I",
    epithet: "Adiutrix",
    legion: "Legio I Adiutrix",
    poiId: "poi_fortress_i_adiutrix_brigetio",
    fortressLatin: "Castra Brigetio",
    province: "Pannonia Superior",
    modernLocation: "Szony district, Komarom, Hungary",
    center: [18.1352, 47.7314],
  },
  {
    numeral: "I",
    epithet: "Minervia",
    legion: "Legio I Minervia",
    poiId: "poi_fortress_i_minervia_bonna",
    fortressLatin: "Castra Bonnensia",
    province: "Germania Inferior",
    modernLocation: "Bonn, Germany",
    center: [7.0947, 50.7359],
  },
  {
    numeral: "I",
    epithet: "Italica",
    legion: "Legio I Italica",
    poiId: "poi_fortress_i_italica_novae",
    fortressLatin: "Castra Novae",
    province: "Moesia Inferior",
    modernLocation: "near Svishtov, Bulgaria",
    center: [25.3936, 43.6203],
  },
  {
    numeral: "II",
    epithet: "Adiutrix",
    legion: "Legio II Adiutrix",
    poiId: "poi_fortress_ii_adiutrix_aquincum",
    fortressLatin: "Castra Aquincum",
    province: "Pannonia Inferior",
    modernLocation: "Obuda, Budapest, Hungary",
    center: [19.0508, 47.5651],
  },
  {
    numeral: "II",
    epithet: "Augusta",
    legion: "Legio II Augusta",
    poiId: "poi_fortress_ii_augusta_isca",
    fortressLatin: "Isca Augusta",
    province: "Britannia",
    modernLocation: "Caerleon, Newport, Wales, UK",
    center: [-2.958, 51.6117],
  },
  {
    numeral: "II",
    epithet: "Traiana Fortis",
    legion: "Legio II Traiana Fortis",
    poiId: "poi_fortress_ii_traiana_fortis_caparcotna",
    fortressLatin: "Castra apud Caparcotna",
    province: "Iudaea",
    modernLocation: "Kefar 'Otnay / Legio junction, near Megiddo, Israel",
    center: [35.171, 32.5715],
  },
  {
    numeral: "III",
    epithet: "Augusta",
    legion: "Legio III Augusta",
    poiId: "poi_fortress_iii_augusta_lambaesis",
    fortressLatin: "Castra Lambaesis",
    province: "Africa Proconsularis (Numidia military district)",
    modernLocation: "Tazoult-Lambese, Algeria",
    center: [6.2611, 35.4936],
  },
  {
    numeral: "III",
    epithet: "Cyrenaica",
    legion: "Legio III Cyrenaica",
    poiId: "poi_fortress_iii_cyrenaica_bostra",
    fortressLatin: "Castra Bostra",
    province: "Arabia",
    modernLocation: "Bosra, Syria",
    center: [36.4817, 32.5177],
  },
  {
    numeral: "III",
    epithet: "Gallica",
    legion: "Legio III Gallica",
    poiId: "poi_fortress_iii_gallica_raphanaea",
    fortressLatin: "Raphanaea",
    province: "Syria",
    modernLocation: "Rafniye, Hama Governorate, Syria",
    center: [36.3727, 34.9263],
  },
  {
    numeral: "IV",
    epithet: "Flavia Felix",
    legion: "Legio IV Flavia Felix",
    poiId: "poi_fortress_iv_flavia_felix_singidunum",
    fortressLatin: "Castra Singidunum",
    province: "Moesia Superior",
    modernLocation: "Kalemegdan, Belgrade, Serbia",
    center: [20.4487, 44.8225],
  },
  {
    numeral: "IV",
    epithet: "Scythica",
    legion: "Legio IV Scythica",
    poiId: "poi_fortress_iv_scythica_zeugma",
    fortressLatin: "Castra Zeugma",
    province: "Syria",
    modernLocation: "Belkis, Gaziantep Province, Turkey",
    center: [37.8658, 37.0586],
  },
  {
    numeral: "V",
    epithet: "Macedonica",
    legion: "Legio V Macedonica",
    poiId: "poi_fortress_v_macedonica_troesmis",
    fortressLatin: "Castra Troesmis",
    province: "Moesia Inferior",
    modernLocation: "Turcoaia, Tulcea County, Romania",
    center: [28.1951, 45.1432],
  },
  {
    numeral: "VI",
    epithet: "Ferrata",
    legion: "Legio VI Ferrata",
    poiId: "poi_fortress_vi_ferrata_caparcotna",
    fortressLatin: "Castra apud Caparcotna",
    province: "Iudaea",
    modernLocation: "Legio/Kefar 'Otnay, near Megiddo Junction, Israel",
    center: [35.1703, 32.5722],
  },
  {
    numeral: "VI",
    epithet: "Victrix",
    legion: "Legio VI Victrix",
    poiId: "poi_fortress_vi_victrix_vetera",
    fortressLatin: "Vetera II",
    province: "Germania Inferior",
    modernLocation: "Birten, near Xanten, Germany",
    center: [6.4515, 51.6672],
  },
  {
    numeral: "VII",
    epithet: "Claudia",
    legion: "Legio VII Claudia",
    poiId: "poi_fortress_vii_claudia_viminacium",
    fortressLatin: "Castra Viminacium",
    province: "Moesia Superior",
    modernLocation: "near Kostolac, Serbia",
    center: [21.2214, 44.7369],
  },
  {
    numeral: "VIII",
    epithet: "Augusta",
    legion: "Legio VIII Augusta",
    poiId: "poi_fortress_viii_augusta_argentorate",
    fortressLatin: "Argentorate",
    province: "Germania Superior",
    modernLocation: "Strasbourg, France",
    center: [7.7455, 48.5839],
  },
  {
    numeral: "IX",
    epithet: "Hispana",
    legion: "Legio IX Hispana",
    poiId: "poi_fortress_ix_hispana_eboracum",
    fortressLatin: "Eboracum",
    province: "Britannia",
    modernLocation: "York, England, UK",
    center: [-1.0873, 53.96],
  },
  {
    numeral: "X",
    epithet: "Fretensis",
    legion: "Legio X Fretensis",
    poiId: "poi_fortress_x_fretensis_jerusalem",
    fortressLatin: "Castra Hierosolyma",
    province: "Iudaea",
    modernLocation: "Old City, Jerusalem",
    center: [35.227, 31.7739],
  },
  {
    numeral: "X",
    epithet: "Gemina",
    legion: "Legio X Gemina",
    poiId: "poi_fortress_x_gemina_vindobona",
    fortressLatin: "Vindobona",
    province: "Pannonia Superior",
    modernLocation: "Vienna city center, Austria",
    center: [16.3728, 48.2094],
  },
  {
    numeral: "XI",
    epithet: "Claudia",
    legion: "Legio XI Claudia",
    poiId: "poi_fortress_xi_claudia_durostorum",
    fortressLatin: "Castra Durostorum",
    province: "Moesia Inferior",
    modernLocation: "Silistra, Bulgaria",
    center: [27.2622, 44.1175],
  },
  {
    numeral: "XII",
    epithet: "Fulminata",
    legion: "Legio XII Fulminata",
    poiId: "poi_fortress_xii_fulminata_melitene",
    fortressLatin: "Melitene",
    province: "Cappadocia",
    modernLocation: "Battalgazi, near Malatya, Turkey",
    center: [38.3612, 38.3822],
  },
  {
    numeral: "XIII",
    epithet: "Gemina",
    legion: "Legio XIII Gemina",
    poiId: "poi_fortress_xiii_gemina_apulum",
    fortressLatin: "Castra Apulum",
    province: "Dacia",
    modernLocation: "Alba Iulia, Romania",
    center: [23.5808, 46.0733],
  },
  {
    numeral: "XIV",
    epithet: "Gemina",
    legion: "Legio XIV Gemina",
    poiId: "poi_fortress_xiv_gemina_carnuntum",
    fortressLatin: "Carnuntum",
    province: "Pannonia Superior",
    modernLocation: "Petronell-Carnuntum / Bad Deutsch-Altenburg, Austria",
    center: [16.8614, 48.1133],
  },
  {
    numeral: "XV",
    epithet: "Apollinaris",
    legion: "Legio XV Apollinaris",
    poiId: "poi_fortress_xv_apollinaris_satala",
    fortressLatin: "Satala",
    province: "Cappadocia",
    modernLocation: "Sadak, Gumushane Province, Turkey",
    center: [39.5979, 40.0277],
  },
  {
    numeral: "XX",
    epithet: "Valeria Victrix",
    legion: "Legio XX Valeria Victrix",
    poiId: "poi_fortress_xx_valeria_victrix_deva",
    fortressLatin: "Deva Victrix",
    province: "Britannia",
    modernLocation: "Chester, England, UK",
    center: [-2.8908, 53.1917],
  },
  {
    numeral: "XXII",
    epithet: "Deiotariana",
    legion: "Legio XXII Deiotariana",
    poiId: "poi_fortress_xxii_deiotariana_nicopolis",
    fortressLatin: "Nicopolis",
    province: "Aegyptus",
    modernLocation: "Sidi Gaber area, east Alexandria, Egypt",
    center: [29.95, 31.2333],
  },
  {
    numeral: "XXII",
    epithet: "Primigenia",
    legion: "Legio XXII Primigenia",
    poiId: "poi_fortress_xxii_primigenia_mogontiacum",
    fortressLatin: "Mogontiacum",
    province: "Germania Superior",
    modernLocation: "Mainz, Germany",
    center: [8.2705, 49.9987],
  },
  {
    numeral: "XXX",
    epithet: "Ulpia Victrix",
    legion: "Legio XXX Ulpia Victrix",
    poiId: "poi_fortress_xxx_ulpia_victrix_brigetio",
    fortressLatin: "Castra Brigetio",
    province: "Pannonia Superior",
    modernLocation: "Szony district, Komarom, Hungary",
    center: [18.1352, 47.7314],
  },
];
