/** Registry of every archaeological site with street-level detail on the map.
 * Feeds the site-jump panel and the click-handler's "modern location / province" line.
 *
 * NAMING RULE (do not break):
 * `display` uses the name a general English-speaking Google-Maps user would recognise.
 *  - Living modern city on top of the Roman core → modern city name (Milan, Trier, Merida).
 *  - Pure archaeological park → site name (Timgad, Volubilis, Palmyra).
 *  - No parenthetical alternates in `display`. If the Roman name is essential context,
 *    put it inside the blurb (e.g. "Roman Mediolanum..." or "known to Romans as Ariminum").
 *  - No diacritics in `display` (write "Merida", not "Mérida"); accented form may live in blurb.
 *  - No abbreviations, no "(city center)" qualifiers, no ancient-vs-modern parens.
 *  - `province` stays in Latin (English scholarship standard).
 *  - `modernCountry` in plain English ("United Kingdom", not "UK"). */

export type SiteInfo = {
  slug: string;
  display: string;
  province: string;      // Roman province name in 117 CE
  modernCountry: string; // for the quick-jump list
  center: [number, number]; // [lng, lat]
  zoom: number;
  founded: string;       // human string (e.g., "~350 BCE" or "founded 100 CE by Trajan")
  blurb: string;         // one-liner for the panel card
  today: string;         // "On this spot today" — one sentence on the modern-day status of the site
  /** Set only for sites whose map view does NOT represent a living 117 CE snapshot — e.g. a
   * site destroyed before 117 (Pompeii, Herculaneum), shown here from its excavated ruin state.
   * Triggers PhaseBanner.tsx on the map and a matching notice on /site/[slug]. Every other site
   * is a thriving 117 CE city and needs no note — omit rather than stating the obvious. */
  snapshotNote?: string;
};

export const SITES: SiteInfo[] = [
  { slug: "ostia",       display: "Ostia Antica",   province: "Italia",         modernCountry: "Italy",       center: [12.2911, 41.7550], zoom: 16.5,
    founded: "~350 BCE (castrum)",
    blurb: "Rome's port at the mouth of the Tiber, at its commercial peak under Trajan.",
    today: "An uninhabited archaeological park near Rome's Fiumicino airport; no modern town overlies it, so the ancient street grid, warehouses, and theatre are fully walkable." },
  { slug: "pompeii",     display: "Pompeii",        province: "Italia",         modernCountry: "Italy",       center: [14.4853, 40.7495], zoom: 16.5,
    founded: "6th c. BCE (Oscan)",
    blurb: "Buried 79 CE by Vesuvius. Frozen at that moment — houses, shops, graffiti and all.",
    today: "An uninhabited, fully excavated UNESCO World Heritage site and one of Italy's most-visited attractions, still yielding new discoveries from the 79 CE eruption." ,
    snapshotNote: "Buried by Vesuvius 38 years before this map's 117 CE snapshot. Shown here from its excavated ruins, not as a living city of the empire." },
  { slug: "herculaneum", display: "Herculaneum",    province: "Italia",         modernCountry: "Italy",       center: [14.3480, 40.8060], zoom: 17.5,
    founded: "6th c. BCE",
    blurb: "Coastal resort town buried by Vesuvius. Wood, papyri, and food survived under 20m of pyroclastic mud.",
    today: "Only partly excavated; the modern town of Ercolano sits atop much of the unexcavated remains, UNESCO-listed jointly with Pompeii." ,
    snapshotNote: "Buried by Vesuvius 38 years before this map's 117 CE snapshot. Shown here from its excavated ruins, not as a living city of the empire." },
  { slug: "ephesus",     display: "Ephesus",        province: "Asia",           modernCountry: "Turkey",      center: [27.3410, 37.9400], zoom: 16.5,
    founded: "10th c. BCE (Ionian)",
    blurb: "Capital of the province of Asia, home of the Temple of Artemis (one of the Seven Wonders) and the Library of Celsus.",
    today: "An uninhabited UNESCO World Heritage archaeological site by the town of Selcuk, Turkey, one of the best-preserved ancient cities in the Mediterranean." },
  { slug: "timgad",      display: "Timgad",         province: "Numidia",        modernCountry: "Algeria",     center: [6.4690, 35.4842], zoom: 17,
    founded: "100 CE by Trajan",
    blurb: "A veterans' colony founded by Trajan for Legio III Augusta. A textbook Roman grid, 17 years old at our snapshot.",
    today: "Uninhabited since a 7th-century Arab invasion; now a fully excavated, empty UNESCO World Heritage archaeological park in the Aures Mountains near Batna, Algeria." },
  { slug: "djemila",     display: "Djemila",        province: "Numidia",        modernCountry: "Algeria",     center: [5.7350, 36.3200], zoom: 17,
    founded: "96 CE by Nerva",
    blurb: "Mountain colony of veterans (Roman Cuicul), contemporary with Timgad. Its stepped forum climbs the hillside.",
    today: "Uninhabited UNESCO World Heritage Roman ruins on a mountain plateau, prized for their mosaics, near a small namesake village in northern Algeria." },
  { slug: "volubilis",   display: "Volubilis",      province: "Mauretania Tingitana", modernCountry: "Morocco", center: [-5.5540, 34.0750], zoom: 16.5,
    founded: "3rd c. BCE (Berber)",
    blurb: "Frontier city at the edge of the empire, only recently annexed (44 CE). Olive-oil boom town.",
    today: "An uninhabited UNESCO World Heritage site near Meknes, Morocco; abandoned in the 11th century, its stones later quarried to help build Meknes." },
  { slug: "leptismagna", display: "Leptis Magna",   province: "Africa Proconsularis", modernCountry: "Libya",  center: [14.2930, 32.6380], zoom: 16.5,
    founded: "1000 BCE (Phoenician)",
    blurb: "Phoenician foundation, later home of emperor Septimius Severus. Its 2nd-century monumental core was still being planned in 117 CE.",
    today: "An uninhabited UNESCO World Heritage site on Libya's coast, well preserved, and reopening to visitors as Libya's tourism slowly recovers." },
  { slug: "sabratha",    display: "Sabratha",       province: "Africa Proconsularis", modernCountry: "Libya",  center: [12.4850, 32.8040], zoom: 16.5,
    founded: "5th c. BCE",
    blurb: "One of the three cities of Tripolitania. Its theatre is one of the largest surviving anywhere in North Africa.",
    today: "An uninhabited UNESCO World Heritage site on Libya's coast, placed on UNESCO's List of World Heritage in Danger in 2016 due to conflict-related damage and neglect." },
  { slug: "jerash",      display: "Jerash",         province: "Arabia Petraea", modernCountry: "Jordan",      center: [35.8920, 32.2780], zoom: 16,
    founded: "170 BCE (Seleucid)",
    blurb: "Best-preserved of the Decapolis cities (Roman Gerasa). Oval forum, colonnaded cardo, Temple of Artemis.",
    today: "A living Jordanian city of around 50,000 whose homes sit alongside ancient Gerasa's ruins, one of the best-preserved Greco-Roman cities outside Italy." },
  { slug: "palmyra",     display: "Palmyra",        province: "Syria",          modernCountry: "Syria",       center: [38.2690, 34.5500], zoom: 16,
    founded: "1st c. BCE (Aramean)",
    blurb: "Caravan city on the trade route between Rome and the Silk Road. Great colonnaded street, Temple of Bel.",
    today: "Uninhabited and badly damaged by ISIS occupation from 2015 to 2017, which destroyed the Temple of Bel, the Baalshamin temple, and the Arch of Triumph; restoration efforts continue." },
  { slug: "baalbek",     display: "Baalbek",        province: "Syria",          modernCountry: "Lebanon",     center: [36.2040, 34.0060], zoom: 17,
    founded: "1st c. BCE (Roman colony)",
    blurb: "Roman Heliopolis. Temple of Jupiter — one of the largest sanctuaries in the empire. Still under construction in Trajan's day.",
    today: "A living Lebanese city of roughly 80,000 in the Bekaa Valley; its UNESCO-listed Roman temples of Jupiter and Bacchus stand within the modern town." },
  { slug: "rome",        display: "Rome",           province: "Italia",         modernCountry: "Italy",       center: [12.4870, 41.8920], zoom: 15,
    founded: "753 BCE (traditional)",
    blurb: "Caput mundi. Around 1 million people in 117 CE — the largest city on earth for centuries either side.",
    today: "Italy's capital of nearly 3 million people; the Colosseum, Forum, and Palatine form a fenced, uninhabited archaeological park inside the UNESCO-listed historic centre." },
  { slug: "aquincum",    display: "Aquincum",       province: "Pannonia",       modernCountry: "Hungary",     center: [19.0480, 47.5670], zoom: 16.5,
    founded: "89 CE (legionary fortress)",
    blurb: "Base of Legio II Adiutrix on the Danube frontier. The proconsul Hadrian lived here just before becoming emperor in 117.",
    today: "Buried beneath modern Budapest's Obuda district; an open-air ruin garden and museum preserve excavated sections within the living city." },
  { slug: "carnuntum",   display: "Carnuntum",      province: "Pannonia",       modernCountry: "Austria",     center: [16.8770, 48.1160], zoom: 16,
    founded: "40 CE",
    blurb: "Major Danube legionary base and the civilian city that grew beside it. Marcus Aurelius later wrote parts of the Meditations here.",
    today: "An uninhabited archaeological park and open-air museum near Petronell-Carnuntum, Austria, with reconstructed Roman houses, part of the UNESCO Danube Limes." },
  { slug: "vindolanda",  display: "Vindolanda",     province: "Britannia",      modernCountry: "United Kingdom", center: [-2.3612, 54.9910], zoom: 17,
    founded: "85 CE",
    blurb: "Auxiliary fort south of what became Hadrian's Wall. The wooden Vindolanda tablets — Rome's oldest written documents from Britain — come from around our snapshot.",
    today: "An uninhabited Roman fort site near Hexham, England, on Hadrian's Wall's UNESCO frontier, and still an active dig with volunteer excavations every summer." },
  { slug: "trier",       display: "Trier",          province: "Gallia Belgica", modernCountry: "Germany",     center: [6.6440, 49.7520], zoom: 15.5,
    founded: "16 BCE by Augustus",
    blurb: "Augusta Treverorum, Roman capital of northern Gaul. Later imperial residence and one of the empire's biggest cities. In 117 CE, a booming provincial capital.",
    today: "A living German city of around 106,000; its Roman monuments, including the Porta Nigra, baths, and bridge, form a UNESCO World Heritage Site standing throughout the modern town." },
  { slug: "xanten",      display: "Xanten",         province: "Germania Inferior", modernCountry: "Germany",  center: [6.4415, 51.6600], zoom: 16,
    founded: "~100 CE by Trajan",
    blurb: "Colonia Ulpia Traiana, a Trajanic colonia on the Rhine named for the emperor. Fresh-built at our 117 CE snapshot — mostly veterans of the Rhine legions.",
    today: "Germany's largest open-air archaeological park, built over Roman Colonia Ulpia Traiana with full-scale reconstructed buildings, part of the UNESCO Lower German Limes." },
  { slug: "corinth",     display: "Corinth",        province: "Achaea",         modernCountry: "Greece",      center: [22.8880, 37.9070], zoom: 16.5,
    founded: "44 BCE (re-founded by Caesar)",
    blurb: "Provincial capital of Achaea, re-founded by Caesar over the ruins of the Greek city Rome had destroyed a century earlier.",
    today: "Uninhabited ruins in the village of Ancient Corinth, a few kilometers from the modern city of Corinth; excavations by the American School continue today." },
  { slug: "athens",      display: "Athens",         province: "Achaea",         modernCountry: "Greece",      center: [23.7260, 37.9750], zoom: 17,
    founded: "1st c. BCE (Roman agora)",
    blurb: "Under Rome but coasting on its glorious past. Hadrian would soon add his Library, arch, and Olympieion.",
    today: "Greece's capital and largest metropolis; the Acropolis and Ancient Agora are fenced UNESCO World Heritage sites within the living city." },
  { slug: "delphi",      display: "Delphi",         province: "Achaea",         modernCountry: "Greece",      center: [22.5010, 38.4820], zoom: 17,
    founded: "8th c. BCE",
    blurb: "Sanctuary of Apollo — still a working oracle in 117 CE, though its reputation was fading.",
    today: "An uninhabited archaeological site; the adjacent modern village of Delphi was relocated in 1892 to allow excavation, and the sanctuary is now UNESCO-listed." },
  { slug: "merida",      display: "Merida",         province: "Lusitania",      modernCountry: "Spain",       center: [-6.3390, 38.9160], zoom: 16,
    founded: "25 BCE by Augustus",
    blurb: "Emerita Augusta, capital of Lusitania, founded for veterans of the Cantabrian wars. Its theatre, amphitheatre, and aqueducts are among Spain's best preserved.",
    today: "A living Spanish city of around 60,000, capital of Extremadura; its extensive Roman ruins, including the theatre, amphitheatre, and aqueduct, are woven through the modern town." },
  { slug: "italica",     display: "Italica",        province: "Baetica",        modernCountry: "Spain",       center: [-6.0450, 37.4420], zoom: 16.5,
    founded: "206 BCE by Scipio",
    blurb: "Home town of Trajan and Hadrian. In 117 CE it was still the old veteran colony — Hadrian's new quarter, which would double the city, was still to come.",
    today: "An uninhabited archaeological park near Santiponce, Spain, just outside Seville; birthplace of Trajan and Hadrian, with its older quarter still lying under the modern village." },

  // ── Italia batch ────────────────────────────────────────────────────────────
  { slug: "aquileia",    display: "Aquileia",       province: "Italia",         modernCountry: "Italy",       center: [13.3720, 45.7700], zoom: 16,
    founded: "181 BCE (Latin colony)",
    blurb: "Adriatic gateway to the Danube — a booming port and one of the largest cities in Italy in 117 CE.",
    today: "A small living Italian town of around 3,000 sitting atop a largely unexcavated Roman city; its archaeological area and basilica are a UNESCO World Heritage Site." },
  { slug: "verona",      display: "Verona",         province: "Italia",         modernCountry: "Italy",       center: [10.9980, 45.4400], zoom: 15.5,
    founded: "89 BCE (Roman municipium)",
    blurb: "Prosperous northern-Italy city on the Adige. Its arena, built around 30 CE, was already old when Trajan died.",
    today: "A living city of around 258,000; the Roman arena still hosts a major open-air opera festival each summer, within a UNESCO-listed historic centre." },
  { slug: "ravenna",     display: "Ravenna",        province: "Italia",         modernCountry: "Italy",       center: [12.1980, 44.4180], zoom: 15.5,
    founded: "1st c. BCE (Roman municipium)",
    blurb: "Base of the Classis Ravennas, the Adriatic fleet, from Augustus onward. In 117 CE Ravenna sat directly on the coast — the shore is now 8 km east.",
    today: "A living Italian city of around 160,000; eight Early Christian and Byzantine monuments with famed mosaics are UNESCO World Heritage, woven into the modern town." },
  { slug: "portus",      display: "Portus",         province: "Italia",         modernCountry: "Italy",       center: [12.2570, 41.7780], zoom: 16,
    founded: "42 CE by Claudius",
    blurb: "Rome's imperial harbor. Trajan's inner hexagonal basin was finished just before our snapshot — you can still see its outline today.",
    today: "An uninhabited archaeological site near Rome's Fiumicino airport; the hexagonal basin of Trajan's ancient harbor still survives amid the modern town." },
  { slug: "tivoli",      display: "Tivoli",         province: "Italia",         modernCountry: "Italy",       center: [12.7980, 41.9640], zoom: 16.5,
    founded: "traditional 1215 BCE (Sabine)",
    blurb: "Roman Tibur, a hillside retreat above the Aniene falls. Old sanctuary of Hercules Victor, favored by Rome's senatorial class. Hadrian's villa was still on the drawing board.",
    today: "A living town of around 55,000 near Rome, home to two UNESCO sites: the uninhabited ruins of Hadrian's Villa and the Renaissance gardens of Villa d'Este." },
  { slug: "palestrina",  display: "Palestrina",     province: "Italia",         modernCountry: "Italy",       center: [12.8970, 41.8370], zoom: 16.5,
    founded: "7th c. BCE",
    blurb: "Roman Praeneste. Home to the Sanctuary of Fortuna Primigenia — a vast terraced complex climbing the hillside, one of the most ambitious pieces of architecture the Republic ever built.",
    today: "A living Italian hill town built directly atop the ancient Temple of Fortuna Primigenia; the sanctuary's terraces underlie it, with a museum in the Palazzo Barberini." },
  { slug: "pozzuoli",    display: "Pozzuoli",       province: "Italia",         modernCountry: "Italy",       center: [14.1210, 40.8260], zoom: 16,
    founded: "194 BCE (Roman colony)",
    blurb: "Roman Puteoli, Italy's main port for eastern grain and luxury goods before Portus took over. Its Flavian amphitheatre — the third-largest in the empire — was newly built at our snapshot.",
    today: "A living port city of around 77,000 near Naples; Roman ruins including the Serapeo market and amphitheatre sit within the modern town, beside the active Solfatara volcano." },
  { slug: "baiae",       display: "Baiae",          province: "Italia",         modernCountry: "Italy",       center: [14.0750, 40.8220], zoom: 16.5,
    founded: "2nd c. BCE (resort)",
    blurb: "The emperors' favorite spa. Domed bath halls fed by volcanic hot springs on the Bay of Naples. Trajan and his court would have known it well.",
    today: "Largely submerged; much of the ancient resort now lies underwater in the Bay of Naples, protected as the Baia Underwater Archaeological Park and visited by divers." },
  { slug: "cumae",       display: "Cumae",          province: "Italia",         modernCountry: "Italy",       center: [14.0520, 40.8480], zoom: 16.5,
    founded: "8th c. BCE (Euboean Greek)",
    blurb: "The oldest Greek colony in Italy, home of the Cumaean Sibyl. By 117 CE its acropolis temples were already tourist attractions.",
    today: "An uninhabited archaeological park in the Campi Flegrei near Naples, including the Cave of the Cumaean Sibyl and acropolis temples, with no modern settlement on site." },
  { slug: "capua",       display: "Capua",          province: "Italia",         modernCountry: "Italy",       center: [14.2590, 41.0830], zoom: 16,
    founded: "9th c. BCE (Etruscan)",
    blurb: "Once the second city of Italy, home to a huge amphitheatre that later served as the model for the Colosseum. Its gladiator school was Spartacus's starting point.",
    today: "The ancient city's ruins lie in the modern town of Santa Maria Capua Vetere; its amphitheatre, the second-largest after the Colosseum, was the site of Spartacus's revolt." },
  { slug: "beneventum",  display: "Benevento",      province: "Italia",         modernCountry: "Italy",       center: [14.7770, 41.1300], zoom: 16,
    founded: "268 BCE (Latin colony)",
    blurb: "Roman Beneventum, terminus of the Via Appia and starting point of the Via Traiana. Trajan's Arch here was dedicated in 114 CE — three years old at our snapshot.",
    today: "A living city of around 55,000 in Campania; the near-intact Arch of Trajan still stands astride a street in the modern town." },
  { slug: "paestum",     display: "Paestum",        province: "Italia",         modernCountry: "Italy",       center: [15.0060, 40.4210], zoom: 16.5,
    founded: "600 BCE (Greek Poseidonia)",
    blurb: "A Greek colony absorbed into Rome. Its three Doric temples — 500 years old in 117 CE — were already ancient monuments.",
    today: "An uninhabited UNESCO World Heritage archaeological park near Salerno, home to three of the best-preserved ancient Greek temples in the world." },
  { slug: "brescia",     display: "Brescia",        province: "Italia",         modernCountry: "Italy",       center: [10.2220, 45.5390], zoom: 16.5,
    founded: "89 BCE (Roman municipium)",
    blurb: "Roman Brixia, a northern-Italy city under the Alps. Vespasian's Capitolium — three temples in one — was newly built and dominated the forum.",
    today: "A living city of around 200,000; its Roman forum and Capitolium temple, part of the UNESCO \"Longobards in Italy\" site, stand in the historic centre." },
  { slug: "milan",       display: "Milan",          province: "Italia",         modernCountry: "Italy",       center: [9.1870, 45.4630], zoom: 15,
    founded: "590 BCE (Insubres); Roman 222 BCE",
    blurb: "Roman Mediolanum, the largest city in northern Italy. In 117 CE, a booming provincial hub — not yet the imperial residence it would become in the 3rd century.",
    today: "A major living metropolis of around 1.4 million; Roman-era remains like the Columns of San Lorenzo survive as isolated fragments within the modern city." },
  { slug: "rimini",      display: "Rimini",         province: "Italia",         modernCountry: "Italy",       center: [12.5730, 44.0580], zoom: 16,
    founded: "268 BCE (Latin colony)",
    blurb: "Roman Ariminum, the pivot of Roman north — the Via Flaminia met the Via Aemilia here. Its Arch of Augustus (27 BCE) and Bridge of Tiberius (21 CE) both still stand.",
    today: "A living seaside city of around 150,000; the Arch of Augustus and the Bridge of Tiberius, both still in everyday use, stand within the modern town." },
  { slug: "ancona",      display: "Ancona",         province: "Italia",         modernCountry: "Italy",       center: [13.5100, 43.6220], zoom: 16,
    founded: "387 BCE (Syracusan Greek)",
    blurb: "Adriatic naval harbor. Trajan enlarged its port; his commemorative arch was dedicated in 115 CE, two years before our snapshot.",
    today: "A living port city of around 100,000 on the Adriatic; Trajan's Arch still overlooks the working harbor it was built to commemorate." },
  { slug: "luni",        display: "Luni",           province: "Italia",         modernCountry: "Italy",       center: [10.0200, 44.0620], zoom: 16.5,
    founded: "177 BCE (Roman colony)",
    blurb: "Roman Luna, the marble port. All the white Carrara marble that clad imperial Rome shipped from here.",
    today: "An uninhabited archaeological park near the Tuscany-Liguria border, abandoned after its harbor silted up in the Middle Ages, with a museum nearby at Ortonovo." },
];

export const SITE_META: Record<string, { display: string; province: string }> =
  Object.fromEntries(SITES.map((s) => [s.slug, { display: s.display, province: s.province }]));
